AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket for VaultCart Application
Resources:
  VaultCartS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      # REMEMBER: This name must be unique globally!
      BucketName: vaultcart-s3-unique-cloudformation-12322
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
