import { NextRequest, NextResponse } from "next/server";
import sql from "mssql";

import { executeProcedure, executeBatch, executeQuery } from "@/lib/db"; // Only need executeProcedure now

export async function POST(request: NextRequest) {
  try {
    const { name, email, password, phone, role, address, cardNumber } =
      await request.json();

    let procedureName = "";
    let result;

    if (role === "seller") {
      procedureName = "[Membership].[RegisterSeller]";

      // Use EXECUTE AS to ensure the AppUser context is active for the session
      // const query = `
      //   EXEC [Membership].[RegisterSeller]
      //     @Name = @Name,
      //     @Email = @Email,
      //     @CardNumber = N'@CardNumber',
      //     @PlainPassword = @PlainPassword;
      // `;

      // const query = `EXEC ${procedureName} @Name, @Email, @CardNumber, @PlainPassword`;

      const params = [
        { name: "Name", type: sql.NVarChar(100), value: name },
        { name: "Email", type: sql.NVarChar(255), value: email },
        { name: "CardNumber", type: sql.NVarChar(16), value: cardNumber },
        { name: "PlainPassword", type: sql.NVarChar(100), value: password },
        // {
        //   name: "UserAgent",
        //   type: sql.NVarChar(500),
        //   value: request.headers.get("user-agent") || "Unknown",
        // }, // Add this!
      ];

      result = await executeBatch(procedureName, params);
    } else {
      // CUSTOMER LOGIC
      procedureName = "Membership.RegisterCustomer";
      const query = `
        EXEC ${procedureName}
          @Name = @Name,
          @Email = @Email,
          @Phone = @Phone,
          @Address = @Address,
          @PlainPassword = @PlainPassword;
      `;
      const params = [
        { name: "Name", type: sql.NVarChar(100), value: name },
        { name: "Email", type: sql.NVarChar(255), value: email },
        { name: "Phone", type: sql.NVarChar(20), value: phone || null },
        {
          name: "Address",
          type: sql.NVarChar(sql.MAX),
          value: address || "No Address",
        },
        { name: "PlainPassword", type: sql.NVarChar(100), value: password },
      ];

      result = await executeQuery(query, params);
    }
    const dbData = result.recordset?.[0];

    if (dbData?.Status === "SUCCESS") {
      return NextResponse.json(
        {
          success: true,
          message: `${role} registered successfully.`,
          id: dbData.SellerID || dbData.CustomerID, // Return the ID generated by the DB
        },
        { status: 201 }
      );
    }

    // If the DB returned something other than SUCCESS
    return NextResponse.json(
      {
        success: false,
        error: "Database registration failed.",
      },
      { status: 400 }
    );
    // const query = `EXEC ${procedureName} @Name, @Email, @Phone, @Address, @PlainPassword`;
  } catch (error: any) {
    console.error("Registration Error:", error.message);

    // Improved error feedback for debugging metadata
    return NextResponse.json(
      {
        error:
          error.message || "An unexpected error occurred during registration.",
      },
      { status: 500 }
    );
  }
}
